"""
Handle LOC intensive graphic assignments

"""
import os

d_fire_image_paths={'burn': {'all':[
                  os.path.join('graphics','fire_breath','fire1.bmp'),
                  os.path.join('graphics','fire_breath','fire1.bmp'),
                  os.path.join('graphics','fire_breath','fire2.bmp'),
                  os.path.join('graphics','fire_breath','fire2.bmp'),
                  os.path.join('graphics','fire_breath','fire3.bmp'),
                  os.path.join('graphics','fire_breath','fire3.bmp'),
                  os.path.join('graphics','fire_breath','fire4.bmp'),
                  os.path.join('graphics','fire_breath','fire4.bmp'),
                  os.path.join('graphics','fire_breath','fire5.bmp'),
                  os.path.join('graphics','fire_breath','fire5.bmp'),
                  os.path.join('graphics','fire_breath','fire6.bmp'),
                  os.path.join('graphics','fire_breath','fire6.bmp'),
                  os.path.join('graphics','fire_breath','fire6.bmp')
                  ]
                    },
                   'paused':{'all':[
                  os.path.join('graphics','fire_breath','paused fire0.bmp')]
                   }
                }

d_knight_image_paths={'attack': {'e': [os.path.join('graphics','knight','attack e0000.bmp'),
                  os.path.join('graphics','knight','attack e0001.bmp'),
                  os.path.join('graphics','knight','attack e0002.bmp'),
                  os.path.join('graphics','knight','attack e0003.bmp'),
                  os.path.join('graphics','knight','attack e0004.bmp'),
                  os.path.join('graphics','knight','attack e0005.bmp'),
                  os.path.join('graphics','knight','attack e0006.bmp'),
                  os.path.join('graphics','knight','attack e0007.bmp'),
                  os.path.join('graphics','knight','attack e0008.bmp'),
                  os.path.join('graphics','knight','attack e0009.bmp'),
                  os.path.join('graphics','knight','attack e0010.bmp'),
                  os.path.join('graphics','knight','attack e0011.bmp'),
                  os.path.join('graphics','knight','attack e0012.bmp')],
            'n': [os.path.join('graphics','knight','attack n0000.bmp'),
                  os.path.join('graphics','knight','attack n0001.bmp'),
                  os.path.join('graphics','knight','attack n0002.bmp'),
                  os.path.join('graphics','knight','attack n0003.bmp'),
                  os.path.join('graphics','knight','attack n0004.bmp'),
                  os.path.join('graphics','knight','attack n0005.bmp'),
                  os.path.join('graphics','knight','attack n0006.bmp'),
                  os.path.join('graphics','knight','attack n0007.bmp'),
                  os.path.join('graphics','knight','attack n0008.bmp'),
                  os.path.join('graphics','knight','attack n0009.bmp'),
                  os.path.join('graphics','knight','attack n0010.bmp'),
                  os.path.join('graphics','knight','attack n0011.bmp'),
                  os.path.join('graphics','knight','attack n0012.bmp')],
            'ne': [os.path.join('graphics','knight','attack ne0000.bmp'),
                   os.path.join('graphics','knight','attack ne0001.bmp'),
                   os.path.join('graphics','knight','attack ne0002.bmp'),
                   os.path.join('graphics','knight','attack ne0003.bmp'),
                   os.path.join('graphics','knight','attack ne0004.bmp'),
                   os.path.join('graphics','knight','attack ne0005.bmp'),
                   os.path.join('graphics','knight','attack ne0006.bmp'),
                   os.path.join('graphics','knight','attack ne0007.bmp'),
                   os.path.join('graphics','knight','attack ne0008.bmp'),
                   os.path.join('graphics','knight','attack ne0009.bmp'),
                   os.path.join('graphics','knight','attack ne0010.bmp'),
                   os.path.join('graphics','knight','attack ne0011.bmp'),
                   os.path.join('graphics','knight','attack ne0012.bmp')],
            'nw': [os.path.join('graphics','knight','attack nw0000.bmp'),
                   os.path.join('graphics','knight','attack nw0001.bmp'),
                   os.path.join('graphics','knight','attack nw0002.bmp'),
                   os.path.join('graphics','knight','attack nw0003.bmp'),
                   os.path.join('graphics','knight','attack nw0004.bmp'),
                   os.path.join('graphics','knight','attack nw0005.bmp'),
                   os.path.join('graphics','knight','attack nw0006.bmp'),
                   os.path.join('graphics','knight','attack nw0007.bmp'),
                   os.path.join('graphics','knight','attack nw0008.bmp'),
                   os.path.join('graphics','knight','attack nw0009.bmp'),
                   os.path.join('graphics','knight','attack nw0010.bmp'),
                   os.path.join('graphics','knight','attack nw0011.bmp'),
                   os.path.join('graphics','knight','attack nw0012.bmp')],
            's': [os.path.join('graphics','knight','attack s0000.bmp'),
                  os.path.join('graphics','knight','attack s0001.bmp'),
                  os.path.join('graphics','knight','attack s0002.bmp'),
                  os.path.join('graphics','knight','attack s0003.bmp'),
                  os.path.join('graphics','knight','attack s0004.bmp'),
                  os.path.join('graphics','knight','attack s0005.bmp'),
                  os.path.join('graphics','knight','attack s0006.bmp'),
                  os.path.join('graphics','knight','attack s0007.bmp'),
                  os.path.join('graphics','knight','attack s0008.bmp'),
                  os.path.join('graphics','knight','attack s0009.bmp'),
                  os.path.join('graphics','knight','attack s0010.bmp'),
                  os.path.join('graphics','knight','attack s0011.bmp'),
                  os.path.join('graphics','knight','attack s0012.bmp')],
            'se': [os.path.join('graphics','knight','attack se0000.bmp'),
                   os.path.join('graphics','knight','attack se0001.bmp'),
                   os.path.join('graphics','knight','attack se0002.bmp'),
                   os.path.join('graphics','knight','attack se0003.bmp'),
                   os.path.join('graphics','knight','attack se0004.bmp'),
                   os.path.join('graphics','knight','attack se0005.bmp'),
                   os.path.join('graphics','knight','attack se0006.bmp'),
                   os.path.join('graphics','knight','attack se0007.bmp'),
                   os.path.join('graphics','knight','attack se0008.bmp'),
                   os.path.join('graphics','knight','attack se0009.bmp'),
                   os.path.join('graphics','knight','attack se0010.bmp'),
                   os.path.join('graphics','knight','attack se0011.bmp'),
                   os.path.join('graphics','knight','attack se0012.bmp')],
            'sw': [os.path.join('graphics','knight','attack sw0000.bmp'),
                   os.path.join('graphics','knight','attack sw0001.bmp'),
                   os.path.join('graphics','knight','attack sw0002.bmp'),
                   os.path.join('graphics','knight','attack sw0003.bmp'),
                   os.path.join('graphics','knight','attack sw0004.bmp'),
                   os.path.join('graphics','knight','attack sw0005.bmp'),
                   os.path.join('graphics','knight','attack sw0006.bmp'),
                   os.path.join('graphics','knight','attack sw0007.bmp'),
                   os.path.join('graphics','knight','attack sw0008.bmp'),
                   os.path.join('graphics','knight','attack sw0009.bmp'),
                   os.path.join('graphics','knight','attack sw0010.bmp'),
                   os.path.join('graphics','knight','attack sw0011.bmp'),
                   os.path.join('graphics','knight','attack sw0012.bmp')],
            'w': [os.path.join('graphics','knight','attack w0000.bmp'),
                  os.path.join('graphics','knight','attack w0001.bmp'),
                  os.path.join('graphics','knight','attack w0002.bmp'),
                  os.path.join('graphics','knight','attack w0003.bmp'),
                  os.path.join('graphics','knight','attack w0004.bmp'),
                  os.path.join('graphics','knight','attack w0005.bmp'),
                  os.path.join('graphics','knight','attack w0006.bmp'),
                  os.path.join('graphics','knight','attack w0007.bmp'),
                  os.path.join('graphics','knight','attack w0008.bmp'),
                  os.path.join('graphics','knight','attack w0009.bmp'),
                  os.path.join('graphics','knight','attack w0010.bmp'),
                  os.path.join('graphics','knight','attack w0011.bmp'),
                  os.path.join('graphics','knight','attack w0012.bmp')]},
 'been hit': {'e': [os.path.join('graphics','knight','been hit e0000.bmp'),
                    os.path.join('graphics','knight','been hit e0001.bmp'),
                    os.path.join('graphics','knight','been hit e0002.bmp'),
                    os.path.join('graphics','knight','been hit e0003.bmp'),
                    os.path.join('graphics','knight','been hit e0004.bmp'),
                    os.path.join('graphics','knight','been hit e0005.bmp'),
                    os.path.join('graphics','knight','been hit e0006.bmp'),
                    os.path.join('graphics','knight','been hit e0007.bmp'),
                    os.path.join('graphics','knight','been hit e0008.bmp')],
              'n': [os.path.join('graphics','knight','been hit n0000.bmp'),
                    os.path.join('graphics','knight','been hit n0001.bmp'),
                    os.path.join('graphics','knight','been hit n0002.bmp'),
                    os.path.join('graphics','knight','been hit n0003.bmp'),
                    os.path.join('graphics','knight','been hit n0004.bmp'),
                    os.path.join('graphics','knight','been hit n0005.bmp'),
                    os.path.join('graphics','knight','been hit n0006.bmp'),
                    os.path.join('graphics','knight','been hit n0007.bmp'),
                    os.path.join('graphics','knight','been hit n0008.bmp')],
              'ne': [os.path.join('graphics','knight','been hit ne0000.bmp'),
                     os.path.join('graphics','knight','been hit ne0001.bmp'),
                     os.path.join('graphics','knight','been hit ne0002.bmp'),
                     os.path.join('graphics','knight','been hit ne0003.bmp'),
                     os.path.join('graphics','knight','been hit ne0004.bmp'),
                     os.path.join('graphics','knight','been hit ne0005.bmp'),
                     os.path.join('graphics','knight','been hit ne0006.bmp'),
                     os.path.join('graphics','knight','been hit ne0007.bmp'),
                     os.path.join('graphics','knight','been hit ne0008.bmp')],
              'nw': [os.path.join('graphics','knight','been hit nw0000.bmp'),
                     os.path.join('graphics','knight','been hit nw0001.bmp'),
                     os.path.join('graphics','knight','been hit nw0002.bmp'),
                     os.path.join('graphics','knight','been hit nw0003.bmp'),
                     os.path.join('graphics','knight','been hit nw0004.bmp'),
                     os.path.join('graphics','knight','been hit nw0005.bmp'),
                     os.path.join('graphics','knight','been hit nw0006.bmp'),
                     os.path.join('graphics','knight','been hit nw0007.bmp'),
                     os.path.join('graphics','knight','been hit nw0008.bmp')],
              's': [os.path.join('graphics','knight','been hit s0000.bmp'),
                    os.path.join('graphics','knight','been hit s0001.bmp'),
                    os.path.join('graphics','knight','been hit s0002.bmp'),
                    os.path.join('graphics','knight','been hit s0003.bmp'),
                    os.path.join('graphics','knight','been hit s0004.bmp'),
                    os.path.join('graphics','knight','been hit s0005.bmp'),
                    os.path.join('graphics','knight','been hit s0006.bmp'),
                    os.path.join('graphics','knight','been hit s0007.bmp'),
                    os.path.join('graphics','knight','been hit s0008.bmp')],
              'se': [os.path.join('graphics','knight','been hit se0000.bmp'),
                     os.path.join('graphics','knight','been hit se0001.bmp'),
                     os.path.join('graphics','knight','been hit se0002.bmp'),
                     os.path.join('graphics','knight','been hit se0003.bmp'),
                     os.path.join('graphics','knight','been hit se0004.bmp'),
                     os.path.join('graphics','knight','been hit se0005.bmp'),
                     os.path.join('graphics','knight','been hit se0006.bmp'),
                     os.path.join('graphics','knight','been hit se0007.bmp'),
                     os.path.join('graphics','knight','been hit se0008.bmp')],
              'sw': [os.path.join('graphics','knight','been hit sw0000.bmp'),
                     os.path.join('graphics','knight','been hit sw0001.bmp'),
                     os.path.join('graphics','knight','been hit sw0002.bmp'),
                     os.path.join('graphics','knight','been hit sw0003.bmp'),
                     os.path.join('graphics','knight','been hit sw0004.bmp'),
                     os.path.join('graphics','knight','been hit sw0005.bmp'),
                     os.path.join('graphics','knight','been hit sw0006.bmp'),
                     os.path.join('graphics','knight','been hit sw0007.bmp'),
                     os.path.join('graphics','knight','been hit sw0008.bmp')],
              'w': [os.path.join('graphics','knight','been hit w0000.bmp'),
                    os.path.join('graphics','knight','been hit w0001.bmp'),
                    os.path.join('graphics','knight','been hit w0002.bmp'),
                    os.path.join('graphics','knight','been hit w0003.bmp'),
                    os.path.join('graphics','knight','been hit w0004.bmp'),
                    os.path.join('graphics','knight','been hit w0005.bmp'),
                    os.path.join('graphics','knight','been hit w0006.bmp'),
                    os.path.join('graphics','knight','been hit w0007.bmp'),
                    os.path.join('graphics','knight','been hit w0008.bmp')]},
 'paused': {'e': [os.path.join('graphics','knight','paused e0000.bmp'),
                  os.path.join('graphics','knight','paused e0001.bmp'),
                  os.path.join('graphics','knight','paused e0002.bmp'),
                  os.path.join('graphics','knight','paused e0003.bmp'),
                  os.path.join('graphics','knight','paused e0004.bmp'),
                  os.path.join('graphics','knight','paused e0005.bmp'),
                  os.path.join('graphics','knight','paused e0006.bmp'),
                  os.path.join('graphics','knight','paused e0007.bmp'),
                  os.path.join('graphics','knight','paused e0008.bmp')],
            'n': [os.path.join('graphics','knight','paused n0000.bmp'),
                  os.path.join('graphics','knight','paused n0001.bmp'),
                  os.path.join('graphics','knight','paused n0002.bmp'),
                  os.path.join('graphics','knight','paused n0003.bmp'),
                  os.path.join('graphics','knight','paused n0004.bmp'),
                  os.path.join('graphics','knight','paused n0005.bmp'),
                  os.path.join('graphics','knight','paused n0006.bmp'),
                  os.path.join('graphics','knight','paused n0007.bmp'),
                  os.path.join('graphics','knight','paused n0008.bmp')],
            'ne': [os.path.join('graphics','knight','paused ne0000.bmp'),
                   os.path.join('graphics','knight','paused ne0001.bmp'),
                   os.path.join('graphics','knight','paused ne0002.bmp'),
                   os.path.join('graphics','knight','paused ne0003.bmp'),
                   os.path.join('graphics','knight','paused ne0004.bmp'),
                   os.path.join('graphics','knight','paused ne0005.bmp'),
                   os.path.join('graphics','knight','paused ne0006.bmp'),
                   os.path.join('graphics','knight','paused ne0007.bmp'),
                   os.path.join('graphics','knight','paused ne0008.bmp')],
            'nw': [os.path.join('graphics','knight','paused nw0000.bmp'),
                   os.path.join('graphics','knight','paused nw0001.bmp'),
                   os.path.join('graphics','knight','paused nw0002.bmp'),
                   os.path.join('graphics','knight','paused nw0003.bmp'),
                   os.path.join('graphics','knight','paused nw0004.bmp'),
                   os.path.join('graphics','knight','paused nw0005.bmp'),
                   os.path.join('graphics','knight','paused nw0006.bmp'),
                   os.path.join('graphics','knight','paused nw0007.bmp'),
                   os.path.join('graphics','knight','paused nw0008.bmp')],
            's': [os.path.join('graphics','knight','paused s0000.bmp'),
                  os.path.join('graphics','knight','paused s0001.bmp'),
                  os.path.join('graphics','knight','paused s0002.bmp'),
                  os.path.join('graphics','knight','paused s0003.bmp'),
                  os.path.join('graphics','knight','paused s0004.bmp'),
                  os.path.join('graphics','knight','paused s0005.bmp'),
                  os.path.join('graphics','knight','paused s0006.bmp'),
                  os.path.join('graphics','knight','paused s0007.bmp'),
                  os.path.join('graphics','knight','paused s0008.bmp')],
            'se': [os.path.join('graphics','knight','paused se0000.bmp'),
                   os.path.join('graphics','knight','paused se0001.bmp'),
                   os.path.join('graphics','knight','paused se0002.bmp'),
                   os.path.join('graphics','knight','paused se0003.bmp'),
                   os.path.join('graphics','knight','paused se0004.bmp'),
                   os.path.join('graphics','knight','paused se0005.bmp'),
                   os.path.join('graphics','knight','paused se0006.bmp'),
                   os.path.join('graphics','knight','paused se0007.bmp'),
                   os.path.join('graphics','knight','paused se0008.bmp')],
            'sw': [os.path.join('graphics','knight','paused sw0000.bmp'),
                   os.path.join('graphics','knight','paused sw0001.bmp'),
                   os.path.join('graphics','knight','paused sw0002.bmp'),
                   os.path.join('graphics','knight','paused sw0003.bmp'),
                   os.path.join('graphics','knight','paused sw0004.bmp'),
                   os.path.join('graphics','knight','paused sw0005.bmp'),
                   os.path.join('graphics','knight','paused sw0006.bmp'),
                   os.path.join('graphics','knight','paused sw0007.bmp'),
                   os.path.join('graphics','knight','paused sw0008.bmp')],
            'w': [os.path.join('graphics','knight','paused w0000.bmp'),
                  os.path.join('graphics','knight','paused w0001.bmp'),
                  os.path.join('graphics','knight','paused w0002.bmp'),
                  os.path.join('graphics','knight','paused w0003.bmp'),
                  os.path.join('graphics','knight','paused w0004.bmp'),
                  os.path.join('graphics','knight','paused w0005.bmp'),
                  os.path.join('graphics','knight','paused w0006.bmp'),
                  os.path.join('graphics','knight','paused w0007.bmp'),
                  os.path.join('graphics','knight','paused w0008.bmp')]},
 'running': {'e': [os.path.join('graphics','knight','running e0000.bmp'),
                   os.path.join('graphics','knight','running e0001.bmp'),
                   os.path.join('graphics','knight','running e0002.bmp'),
                   os.path.join('graphics','knight','running e0003.bmp'),
                   os.path.join('graphics','knight','running e0004.bmp'),
                   os.path.join('graphics','knight','running e0005.bmp'),
                   os.path.join('graphics','knight','running e0006.bmp'),
                   os.path.join('graphics','knight','running e0007.bmp')],
             'n': [os.path.join('graphics','knight','running n0000.bmp'),
                   os.path.join('graphics','knight','running n0001.bmp'),
                   os.path.join('graphics','knight','running n0002.bmp'),
                   os.path.join('graphics','knight','running n0003.bmp'),
                   os.path.join('graphics','knight','running n0004.bmp'),
                   os.path.join('graphics','knight','running n0005.bmp'),
                   os.path.join('graphics','knight','running n0006.bmp'),
                   os.path.join('graphics','knight','running n0007.bmp')],
             'ne': [os.path.join('graphics','knight','running ne0000.bmp'),
                    os.path.join('graphics','knight','running ne0001.bmp'),
                    os.path.join('graphics','knight','running ne0002.bmp'),
                    os.path.join('graphics','knight','running ne0003.bmp'),
                    os.path.join('graphics','knight','running ne0004.bmp'),
                    os.path.join('graphics','knight','running ne0005.bmp'),
                    os.path.join('graphics','knight','running ne0006.bmp'),
                    os.path.join('graphics','knight','running ne0007.bmp')],
             'nw': [os.path.join('graphics','knight','running nw0000.bmp'),
                    os.path.join('graphics','knight','running nw0001.bmp'),
                    os.path.join('graphics','knight','running nw0002.bmp'),
                    os.path.join('graphics','knight','running nw0003.bmp'),
                    os.path.join('graphics','knight','running nw0004.bmp'),
                    os.path.join('graphics','knight','running nw0005.bmp'),
                    os.path.join('graphics','knight','running nw0006.bmp'),
                    os.path.join('graphics','knight','running nw0007.bmp')],
             's': [os.path.join('graphics','knight','running s0000.bmp'),
                   os.path.join('graphics','knight','running s0001.bmp'),
                   os.path.join('graphics','knight','running s0002.bmp'),
                   os.path.join('graphics','knight','running s0003.bmp'),
                   os.path.join('graphics','knight','running s0004.bmp'),
                   os.path.join('graphics','knight','running s0005.bmp'),
                   os.path.join('graphics','knight','running s0006.bmp'),
                   os.path.join('graphics','knight','running s0007.bmp')],
             'se': [os.path.join('graphics','knight','running se0000.bmp'),
                    os.path.join('graphics','knight','running se0001.bmp'),
                    os.path.join('graphics','knight','running se0002.bmp'),
                    os.path.join('graphics','knight','running se0003.bmp'),
                    os.path.join('graphics','knight','running se0004.bmp'),
                    os.path.join('graphics','knight','running se0005.bmp'),
                    os.path.join('graphics','knight','running se0006.bmp'),
                    os.path.join('graphics','knight','running se0007.bmp')],
             'sw': [os.path.join('graphics','knight','running sw0000.bmp'),
                    os.path.join('graphics','knight','running sw0001.bmp'),
                    os.path.join('graphics','knight','running sw0002.bmp'),
                    os.path.join('graphics','knight','running sw0003.bmp'),
                    os.path.join('graphics','knight','running sw0004.bmp'),
                    os.path.join('graphics','knight','running sw0005.bmp'),
                    os.path.join('graphics','knight','running sw0006.bmp'),
                    os.path.join('graphics','knight','running sw0007.bmp')],
             'w': [os.path.join('graphics','knight','running w0000.bmp'),
                   os.path.join('graphics','knight','running w0001.bmp'),
                   os.path.join('graphics','knight','running w0002.bmp'),
                   os.path.join('graphics','knight','running w0003.bmp'),
                   os.path.join('graphics','knight','running w0004.bmp'),
                   os.path.join('graphics','knight','running w0005.bmp'),
                   os.path.join('graphics','knight','running w0006.bmp'),
                   os.path.join('graphics','knight','running w0007.bmp')]},
 'tipping over': {'e': [
                        os.path.join('graphics','knight','tipping over e0000.bmp'),
                        os.path.join('graphics','knight','tipping over e0001.bmp'),
                        os.path.join('graphics','knight','tipping over e0002.bmp'),
                        os.path.join('graphics','knight','tipping over e0003.bmp'),
                        os.path.join('graphics','knight','tipping over e0004.bmp'),
                        os.path.join('graphics','knight','tipping over e0005.bmp'),
                        os.path.join('graphics','knight','tipping over e0006.bmp'),
                        os.path.join('graphics','knight','tipping over e0007.bmp'),
                        os.path.join('graphics','knight','tipping over e0008.bmp')],
                  'n': [os.path.join('graphics','knight','tipping over n0000.bmp'),
                        os.path.join('graphics','knight','tipping over n0001.bmp'),
                        os.path.join('graphics','knight','tipping over n0002.bmp'),
                        os.path.join('graphics','knight','tipping over n0003.bmp'),
                        os.path.join('graphics','knight','tipping over n0004.bmp'),
                        os.path.join('graphics','knight','tipping over n0005.bmp'),
                        os.path.join('graphics','knight','tipping over n0006.bmp'),
                        os.path.join('graphics','knight','tipping over n0007.bmp'),
                        os.path.join('graphics','knight','tipping over n0008.bmp')],
                  'ne': [os.path.join('graphics','knight','tipping over ne0000.bmp'),
                         os.path.join('graphics','knight','tipping over ne0001.bmp'),
                         os.path.join('graphics','knight','tipping over ne0002.bmp'),
                         os.path.join('graphics','knight','tipping over ne0003.bmp'),
                         os.path.join('graphics','knight','tipping over ne0004.bmp'),
                         os.path.join('graphics','knight','tipping over ne0005.bmp'),
                         os.path.join('graphics','knight','tipping over ne0006.bmp'),
                         os.path.join('graphics','knight','tipping over ne0007.bmp'),
                         os.path.join('graphics','knight','tipping over ne0008.bmp')],
                  'nw': [os.path.join('graphics','knight','tipping over nw0000.bmp'),
                         os.path.join('graphics','knight','tipping over nw0001.bmp'),
                         os.path.join('graphics','knight','tipping over nw0002.bmp'),
                         os.path.join('graphics','knight','tipping over nw0003.bmp'),
                         os.path.join('graphics','knight','tipping over nw0004.bmp'),
                         os.path.join('graphics','knight','tipping over nw0005.bmp'),
                         os.path.join('graphics','knight','tipping over nw0006.bmp'),
                         os.path.join('graphics','knight','tipping over nw0007.bmp'),
                         os.path.join('graphics','knight','tipping over nw0008.bmp')],
                  's': [os.path.join('graphics','knight','tipping over s0000.bmp'),
                        os.path.join('graphics','knight','tipping over s0001.bmp'),
                        os.path.join('graphics','knight','tipping over s0002.bmp'),
                        os.path.join('graphics','knight','tipping over s0003.bmp'),
                        os.path.join('graphics','knight','tipping over s0004.bmp'),
                        os.path.join('graphics','knight','tipping over s0005.bmp'),
                        os.path.join('graphics','knight','tipping over s0006.bmp'),
                        os.path.join('graphics','knight','tipping over s0007.bmp'),
                        os.path.join('graphics','knight','tipping over s0008.bmp')],
                  'se': [os.path.join('graphics','knight','tipping over se0000.bmp'),
                         os.path.join('graphics','knight','tipping over se0001.bmp'),
                         os.path.join('graphics','knight','tipping over se0002.bmp'),
                         os.path.join('graphics','knight','tipping over se0003.bmp'),
                         os.path.join('graphics','knight','tipping over se0004.bmp'),
                         os.path.join('graphics','knight','tipping over se0005.bmp'),
                         os.path.join('graphics','knight','tipping over se0006.bmp'),
                         os.path.join('graphics','knight','tipping over se0007.bmp'),
                         os.path.join('graphics','knight','tipping over se0008.bmp')],
                  'sw': [os.path.join('graphics','knight','tipping over sw0000.bmp'),
                         os.path.join('graphics','knight','tipping over sw0001.bmp'),
                         os.path.join('graphics','knight','tipping over sw0002.bmp'),
                         os.path.join('graphics','knight','tipping over sw0003.bmp'),
                         os.path.join('graphics','knight','tipping over sw0004.bmp'),
                         os.path.join('graphics','knight','tipping over sw0005.bmp'),
                         os.path.join('graphics','knight','tipping over sw0006.bmp'),
                         os.path.join('graphics','knight','tipping over sw0007.bmp'),
                         os.path.join('graphics','knight','tipping over sw0008.bmp')],
                  'w': [os.path.join('graphics','knight','tipping over w0000.bmp'),
                        os.path.join('graphics','knight','tipping over w0001.bmp'),
                        os.path.join('graphics','knight','tipping over w0002.bmp'),
                        os.path.join('graphics','knight','tipping over w0003.bmp'),
                        os.path.join('graphics','knight','tipping over w0004.bmp'),
                        os.path.join('graphics','knight','tipping over w0005.bmp'),
                        os.path.join('graphics','knight','tipping over w0006.bmp'),
                        os.path.join('graphics','knight','tipping over w0007.bmp'),
                        os.path.join('graphics','knight','tipping over w0008.bmp')]},
 'walking': {'e': [os.path.join('graphics','knight','walking e0000.bmp'),
                   os.path.join('graphics','knight','walking e0001.bmp'),
                   os.path.join('graphics','knight','walking e0002.bmp'),
                   os.path.join('graphics','knight','walking e0003.bmp'),
                   os.path.join('graphics','knight','walking e0004.bmp'),
                   os.path.join('graphics','knight','walking e0005.bmp'),
                   os.path.join('graphics','knight','walking e0006.bmp'),
                   os.path.join('graphics','knight','walking e0007.bmp')],
             'n': [os.path.join('graphics','knight','walking n0000.bmp'),
                   os.path.join('graphics','knight','walking n0001.bmp'),
                   os.path.join('graphics','knight','walking n0002.bmp'),
                   os.path.join('graphics','knight','walking n0003.bmp'),
                   os.path.join('graphics','knight','walking n0004.bmp'),
                   os.path.join('graphics','knight','walking n0005.bmp'),
                   os.path.join('graphics','knight','walking n0006.bmp'),
                   os.path.join('graphics','knight','walking n0007.bmp')],
             'ne': [os.path.join('graphics','knight','walking ne0000.bmp'),
                    os.path.join('graphics','knight','walking ne0001.bmp'),
                    os.path.join('graphics','knight','walking ne0002.bmp'),
                    os.path.join('graphics','knight','walking ne0003.bmp'),
                    os.path.join('graphics','knight','walking ne0004.bmp'),
                    os.path.join('graphics','knight','walking ne0005.bmp'),
                    os.path.join('graphics','knight','walking ne0006.bmp'),
                    os.path.join('graphics','knight','walking ne0007.bmp')],
             'nw': [os.path.join('graphics','knight','walking nw0000.bmp'),
                    os.path.join('graphics','knight','walking nw0001.bmp'),
                    os.path.join('graphics','knight','walking nw0002.bmp'),
                    os.path.join('graphics','knight','walking nw0003.bmp'),
                    os.path.join('graphics','knight','walking nw0004.bmp'),
                    os.path.join('graphics','knight','walking nw0005.bmp'),
                    os.path.join('graphics','knight','walking nw0006.bmp'),
                    os.path.join('graphics','knight','walking nw0007.bmp')],
             's': [os.path.join('graphics','knight','walking s0000.bmp'),
                   os.path.join('graphics','knight','walking s0001.bmp'),
                   os.path.join('graphics','knight','walking s0002.bmp'),
                   os.path.join('graphics','knight','walking s0003.bmp'),
                   os.path.join('graphics','knight','walking s0004.bmp'),
                   os.path.join('graphics','knight','walking s0005.bmp'),
                   os.path.join('graphics','knight','walking s0006.bmp'),
                   os.path.join('graphics','knight','walking s0007.bmp')],
             'se': [os.path.join('graphics','knight','walking se0000.bmp'),
                    os.path.join('graphics','knight','walking se0001.bmp'),
                    os.path.join('graphics','knight','walking se0002.bmp'),
                    os.path.join('graphics','knight','walking se0003.bmp'),
                    os.path.join('graphics','knight','walking se0004.bmp'),
                    os.path.join('graphics','knight','walking se0005.bmp'),
                    os.path.join('graphics','knight','walking se0006.bmp'),
                    os.path.join('graphics','knight','walking se0007.bmp')],
             'sw': [os.path.join('graphics','knight','walking sw0000.bmp'),
                    os.path.join('graphics','knight','walking sw0001.bmp'),
                    os.path.join('graphics','knight','walking sw0002.bmp'),
                    os.path.join('graphics','knight','walking sw0003.bmp'),
                    os.path.join('graphics','knight','walking sw0004.bmp'),
                    os.path.join('graphics','knight','walking sw0005.bmp'),
                    os.path.join('graphics','knight','walking sw0006.bmp'),
                    os.path.join('graphics','knight','walking sw0007.bmp')],
             'w': [os.path.join('graphics','knight','walking w0000.bmp'),
                   os.path.join('graphics','knight','walking w0001.bmp'),
                   os.path.join('graphics','knight','walking w0002.bmp'),
                   os.path.join('graphics','knight','walking w0003.bmp'),
                   os.path.join('graphics','knight','walking w0004.bmp'),
                   os.path.join('graphics','knight','walking w0005.bmp'),
                   os.path.join('graphics','knight','walking w0006.bmp'),
                   os.path.join('graphics','knight','walking w0007.bmp')]}}

d_dragon_image_paths={'attack': {'e': [os.path.join('graphics','dragon','attack e0000.bmp'),
                  os.path.join('graphics','dragon','attack e0001.bmp'),
                  os.path.join('graphics','dragon','attack e0002.bmp'),
                  os.path.join('graphics','dragon','attack e0003.bmp'),
                  os.path.join('graphics','dragon','attack e0004.bmp'),
                  os.path.join('graphics','dragon','attack e0005.bmp'),
                  os.path.join('graphics','dragon','attack e0006.bmp'),
                  os.path.join('graphics','dragon','attack e0007.bmp'),
                  os.path.join('graphics','dragon','attack e0008.bmp')],
            'n': [os.path.join('graphics','dragon','attack n0000.bmp'),
                  os.path.join('graphics','dragon','attack n0001.bmp'),
                  os.path.join('graphics','dragon','attack n0002.bmp'),
                  os.path.join('graphics','dragon','attack n0003.bmp'),
                  os.path.join('graphics','dragon','attack n0004.bmp'),
                  os.path.join('graphics','dragon','attack n0005.bmp'),
                  os.path.join('graphics','dragon','attack n0006.bmp'),
                  os.path.join('graphics','dragon','attack n0007.bmp'),
                  os.path.join('graphics','dragon','attack n0008.bmp')],
            'ne': [os.path.join('graphics','dragon','attack ne0000.bmp'),
                   os.path.join('graphics','dragon','attack ne0001.bmp'),
                   os.path.join('graphics','dragon','attack ne0002.bmp'),
                   os.path.join('graphics','dragon','attack ne0003.bmp'),
                   os.path.join('graphics','dragon','attack ne0004.bmp'),
                   os.path.join('graphics','dragon','attack ne0005.bmp'),
                   os.path.join('graphics','dragon','attack ne0006.bmp'),
                   os.path.join('graphics','dragon','attack ne0007.bmp'),
                   os.path.join('graphics','dragon','attack ne0008.bmp')],
            'nw': [os.path.join('graphics','dragon','attack nw0000.bmp'),
                   os.path.join('graphics','dragon','attack nw0001.bmp'),
                   os.path.join('graphics','dragon','attack nw0002.bmp'),
                   os.path.join('graphics','dragon','attack nw0003.bmp'),
                   os.path.join('graphics','dragon','attack nw0004.bmp'),
                   os.path.join('graphics','dragon','attack nw0005.bmp'),
                   os.path.join('graphics','dragon','attack nw0006.bmp'),
                   os.path.join('graphics','dragon','attack nw0007.bmp'),
                   os.path.join('graphics','dragon','attack nw0008.bmp')],
            's': [os.path.join('graphics','dragon','attack s0000.bmp'),
                  os.path.join('graphics','dragon','attack s0001.bmp'),
                  os.path.join('graphics','dragon','attack s0002.bmp'),
                  os.path.join('graphics','dragon','attack s0003.bmp'),
                  os.path.join('graphics','dragon','attack s0004.bmp'),
                  os.path.join('graphics','dragon','attack s0005.bmp'),
                  os.path.join('graphics','dragon','attack s0006.bmp'),
                  os.path.join('graphics','dragon','attack s0007.bmp'),
                  os.path.join('graphics','dragon','attack s0008.bmp')],
            'se': [os.path.join('graphics','dragon','attack se0000.bmp'),
                   os.path.join('graphics','dragon','attack se0001.bmp'),
                   os.path.join('graphics','dragon','attack se0002.bmp'),
                   os.path.join('graphics','dragon','attack se0003.bmp'),
                   os.path.join('graphics','dragon','attack se0004.bmp'),
                   os.path.join('graphics','dragon','attack se0005.bmp'),
                   os.path.join('graphics','dragon','attack se0006.bmp'),
                   os.path.join('graphics','dragon','attack se0007.bmp'),
                   os.path.join('graphics','dragon','attack se0008.bmp')],
            'sw': [os.path.join('graphics','dragon','attack sw0000.bmp'),
                   os.path.join('graphics','dragon','attack sw0001.bmp'),
                   os.path.join('graphics','dragon','attack sw0002.bmp'),
                   os.path.join('graphics','dragon','attack sw0003.bmp'),
                   os.path.join('graphics','dragon','attack sw0004.bmp'),
                   os.path.join('graphics','dragon','attack sw0005.bmp'),
                   os.path.join('graphics','dragon','attack sw0006.bmp'),
                   os.path.join('graphics','dragon','attack sw0007.bmp'),
                   os.path.join('graphics','dragon','attack sw0008.bmp')],
            'w': [os.path.join('graphics','dragon','attack w0000.bmp'),
                  os.path.join('graphics','dragon','attack w0001.bmp'),
                  os.path.join('graphics','dragon','attack w0002.bmp'),
                  os.path.join('graphics','dragon','attack w0003.bmp'),
                  os.path.join('graphics','dragon','attack w0004.bmp'),
                  os.path.join('graphics','dragon','attack w0005.bmp'),
                  os.path.join('graphics','dragon','attack w0006.bmp'),
                  os.path.join('graphics','dragon','attack w0007.bmp'),
                  os.path.join('graphics','dragon','attack w0008.bmp')]},
 'paused': {'e': [os.path.join('graphics','dragon','paused e0000.bmp')],
            'n': [os.path.join('graphics','dragon','paused n0000.bmp')],
            'ne': [os.path.join('graphics','dragon','paused ne0000.bmp')],
            'nw': [os.path.join('graphics','dragon','paused nw0000.bmp')],
            's': [os.path.join('graphics','dragon','paused s0000.bmp')],
            'se': [os.path.join('graphics','dragon','paused se0000.bmp')],
            'sw': [os.path.join('graphics','dragon','paused sw0000.bmp')],
            'w': [os.path.join('graphics','dragon','paused w0000.bmp')]},
 'reading': {'e': [os.path.join('graphics','dragon','reading e0000.bmp'),
                   os.path.join('graphics','dragon','reading e0001.bmp'),
                   os.path.join('graphics','dragon','reading e0002.bmp'),
                   os.path.join('graphics','dragon','reading e0003.bmp'),
                   os.path.join('graphics','dragon','reading e0004.bmp'),
                   os.path.join('graphics','dragon','reading e0005.bmp'),
                   os.path.join('graphics','dragon','reading e0006.bmp'),
                   os.path.join('graphics','dragon','reading e0007.bmp'),
                   os.path.join('graphics','dragon','reading e0008.bmp')],
             'n': [os.path.join('graphics','dragon','reading n0000.bmp'),
                   os.path.join('graphics','dragon','reading n0001.bmp'),
                   os.path.join('graphics','dragon','reading n0002.bmp'),
                   os.path.join('graphics','dragon','reading n0003.bmp'),
                   os.path.join('graphics','dragon','reading n0004.bmp'),
                   os.path.join('graphics','dragon','reading n0005.bmp'),
                   os.path.join('graphics','dragon','reading n0006.bmp'),
                   os.path.join('graphics','dragon','reading n0007.bmp'),
                   os.path.join('graphics','dragon','reading n0008.bmp')],
             'ne': [os.path.join('graphics','dragon','reading ne0000.bmp'),
                    os.path.join('graphics','dragon','reading ne0001.bmp'),
                    os.path.join('graphics','dragon','reading ne0002.bmp'),
                    os.path.join('graphics','dragon','reading ne0003.bmp'),
                    os.path.join('graphics','dragon','reading ne0004.bmp'),
                    os.path.join('graphics','dragon','reading ne0005.bmp'),
                    os.path.join('graphics','dragon','reading ne0006.bmp'),
                    os.path.join('graphics','dragon','reading ne0007.bmp'),
                    os.path.join('graphics','dragon','reading ne0008.bmp')],
             'nw': [os.path.join('graphics','dragon','reading nw0000.bmp'),
                    os.path.join('graphics','dragon','reading nw0001.bmp'),
                    os.path.join('graphics','dragon','reading nw0002.bmp'),
                    os.path.join('graphics','dragon','reading nw0003.bmp'),
                    os.path.join('graphics','dragon','reading nw0004.bmp'),
                    os.path.join('graphics','dragon','reading nw0005.bmp'),
                    os.path.join('graphics','dragon','reading nw0006.bmp'),
                    os.path.join('graphics','dragon','reading nw0007.bmp'),
                    os.path.join('graphics','dragon','reading nw0008.bmp')],
             's': [os.path.join('graphics','dragon','reading s0000.bmp'),
                   os.path.join('graphics','dragon','reading s0001.bmp'),
                   os.path.join('graphics','dragon','reading s0002.bmp'),
                   os.path.join('graphics','dragon','reading s0003.bmp'),
                   os.path.join('graphics','dragon','reading s0004.bmp'),
                   os.path.join('graphics','dragon','reading s0005.bmp'),
                   os.path.join('graphics','dragon','reading s0006.bmp'),
                   os.path.join('graphics','dragon','reading s0007.bmp'),
                   os.path.join('graphics','dragon','reading s0008.bmp')],
             'se': [os.path.join('graphics','dragon','reading se0000.bmp'),
                    os.path.join('graphics','dragon','reading se0001.bmp'),
                    os.path.join('graphics','dragon','reading se0002.bmp'),
                    os.path.join('graphics','dragon','reading se0003.bmp'),
                    os.path.join('graphics','dragon','reading se0004.bmp'),
                    os.path.join('graphics','dragon','reading se0005.bmp'),
                    os.path.join('graphics','dragon','reading se0006.bmp'),
                    os.path.join('graphics','dragon','reading se0007.bmp'),
                    os.path.join('graphics','dragon','reading se0008.bmp')],
             'sw': [os.path.join('graphics','dragon','reading sw0000.bmp'),
                    os.path.join('graphics','dragon','reading sw0001.bmp'),
                    os.path.join('graphics','dragon','reading sw0002.bmp'),
                    os.path.join('graphics','dragon','reading sw0003.bmp'),
                    os.path.join('graphics','dragon','reading sw0004.bmp'),
                    os.path.join('graphics','dragon','reading sw0005.bmp'),
                    os.path.join('graphics','dragon','reading sw0006.bmp'),
                    os.path.join('graphics','dragon','reading sw0007.bmp'),
                    os.path.join('graphics','dragon','reading sw0008.bmp')],
             'w': [os.path.join('graphics','dragon','reading w0000.bmp'),
                   os.path.join('graphics','dragon','reading w0001.bmp'),
                   os.path.join('graphics','dragon','reading w0002.bmp'),
                   os.path.join('graphics','dragon','reading w0003.bmp'),
                   os.path.join('graphics','dragon','reading w0004.bmp'),
                   os.path.join('graphics','dragon','reading w0005.bmp'),
                   os.path.join('graphics','dragon','reading w0006.bmp'),
                   os.path.join('graphics','dragon','reading w0007.bmp'),
                   os.path.join('graphics','dragon','reading w0008.bmp')]},
 'running': {'e': [os.path.join('graphics','dragon','running e0000.bmp'),
                   os.path.join('graphics','dragon','running e0001.bmp'),
                   os.path.join('graphics','dragon','running e0002.bmp'),
                   os.path.join('graphics','dragon','running e0003.bmp'),
                   os.path.join('graphics','dragon','running e0004.bmp'),
                   os.path.join('graphics','dragon','running e0005.bmp'),
                   os.path.join('graphics','dragon','running e0006.bmp')],
             'n': [os.path.join('graphics','dragon','running n0000.bmp'),
                   os.path.join('graphics','dragon','running n0001.bmp'),
                   os.path.join('graphics','dragon','running n0002.bmp'),
                   os.path.join('graphics','dragon','running n0003.bmp'),
                   os.path.join('graphics','dragon','running n0004.bmp'),
                   os.path.join('graphics','dragon','running n0005.bmp'),
                   os.path.join('graphics','dragon','running n0006.bmp')],
             'ne': [os.path.join('graphics','dragon','running ne0000.bmp'),
                    os.path.join('graphics','dragon','running ne0001.bmp'),
                    os.path.join('graphics','dragon','running ne0002.bmp'),
                    os.path.join('graphics','dragon','running ne0003.bmp'),
                    os.path.join('graphics','dragon','running ne0004.bmp'),
                    os.path.join('graphics','dragon','running ne0005.bmp'),
                    os.path.join('graphics','dragon','running ne0006.bmp')],
             'nw': [os.path.join('graphics','dragon','running nw0000.bmp'),
                    os.path.join('graphics','dragon','running nw0001.bmp'),
                    os.path.join('graphics','dragon','running nw0002.bmp'),
                    os.path.join('graphics','dragon','running nw0003.bmp'),
                    os.path.join('graphics','dragon','running nw0004.bmp'),
                    os.path.join('graphics','dragon','running nw0005.bmp'),
                    os.path.join('graphics','dragon','running nw0006.bmp')],
             's': [os.path.join('graphics','dragon','running s0000.bmp'),
                   os.path.join('graphics','dragon','running s0001.bmp'),
                   os.path.join('graphics','dragon','running s0002.bmp'),
                   os.path.join('graphics','dragon','running s0003.bmp'),
                   os.path.join('graphics','dragon','running s0004.bmp'),
                   os.path.join('graphics','dragon','running s0005.bmp'),
                   os.path.join('graphics','dragon','running s0006.bmp')],
             'se': [os.path.join('graphics','dragon','running se0000.bmp'),
                    os.path.join('graphics','dragon','running se0001.bmp'),
                    os.path.join('graphics','dragon','running se0002.bmp'),
                    os.path.join('graphics','dragon','running se0003.bmp'),
                    os.path.join('graphics','dragon','running se0004.bmp'),
                    os.path.join('graphics','dragon','running se0005.bmp'),
                    os.path.join('graphics','dragon','running se0006.bmp')],
             'sw': [os.path.join('graphics','dragon','running sw0000.bmp'),
                    os.path.join('graphics','dragon','running sw0001.bmp'),
                    os.path.join('graphics','dragon','running sw0002.bmp'),
                    os.path.join('graphics','dragon','running sw0003.bmp'),
                    os.path.join('graphics','dragon','running sw0004.bmp'),
                    os.path.join('graphics','dragon','running sw0005.bmp'),
                    os.path.join('graphics','dragon','running sw0006.bmp')],
             'w': [os.path.join('graphics','dragon','running w0000.bmp'),
                   os.path.join('graphics','dragon','running w0001.bmp'),
                   os.path.join('graphics','dragon','running w0002.bmp'),
                   os.path.join('graphics','dragon','running w0003.bmp'),
                   os.path.join('graphics','dragon','running w0004.bmp'),
                   os.path.join('graphics','dragon','running w0005.bmp'),
                   os.path.join('graphics','dragon','running w0006.bmp')]},
 'tipping over': {'e': [
                        os.path.join('graphics','dragon','tipping over e0000.bmp'),
                        os.path.join('graphics','dragon','tipping over e0001.bmp'),
                        os.path.join('graphics','dragon','tipping over e0002.bmp'),
                        os.path.join('graphics','dragon','tipping over e0003.bmp'),
                        os.path.join('graphics','dragon','tipping over e0004.bmp'),
                        os.path.join('graphics','dragon','tipping over e0005.bmp'),
                        os.path.join('graphics','dragon','tipping over e0006.bmp'),
                        os.path.join('graphics','dragon','tipping over e0007.bmp'),
                        os.path.join('graphics','dragon','tipping over e0008.bmp'),
                        os.path.join('graphics','dragon','tipping over e0009.bmp'),
                        os.path.join('graphics','dragon','tipping over e0010.bmp')],
                  'n': [os.path.join('graphics','dragon','tipping over n0000.bmp'),
                        os.path.join('graphics','dragon','tipping over n0001.bmp'),
                        os.path.join('graphics','dragon','tipping over n0002.bmp'),
                        os.path.join('graphics','dragon','tipping over n0003.bmp'),
                        os.path.join('graphics','dragon','tipping over n0004.bmp'),
                        os.path.join('graphics','dragon','tipping over n0005.bmp'),
                        os.path.join('graphics','dragon','tipping over n0006.bmp'),
                        os.path.join('graphics','dragon','tipping over n0007.bmp'),
                        os.path.join('graphics','dragon','tipping over n0008.bmp'),
                        os.path.join('graphics','dragon','tipping over n0009.bmp'),
                        os.path.join('graphics','dragon','tipping over n0010.bmp')],
                  'ne': [os.path.join('graphics','dragon','tipping over ne0000.bmp'),
                         os.path.join('graphics','dragon','tipping over ne0001.bmp'),
                         os.path.join('graphics','dragon','tipping over ne0002.bmp'),
                         os.path.join('graphics','dragon','tipping over ne0003.bmp'),
                         os.path.join('graphics','dragon','tipping over ne0004.bmp'),
                         os.path.join('graphics','dragon','tipping over ne0005.bmp'),
                         os.path.join('graphics','dragon','tipping over ne0006.bmp'),
                         os.path.join('graphics','dragon','tipping over ne0007.bmp'),
                         os.path.join('graphics','dragon','tipping over ne0008.bmp'),
                         os.path.join('graphics','dragon','tipping over ne0009.bmp'),
                         os.path.join('graphics','dragon','tipping over ne0010.bmp')],
                  'nw': [os.path.join('graphics','dragon','tipping over nw0000.bmp'),
                         os.path.join('graphics','dragon','tipping over nw0001.bmp'),
                         os.path.join('graphics','dragon','tipping over nw0002.bmp'),
                         os.path.join('graphics','dragon','tipping over nw0003.bmp'),
                         os.path.join('graphics','dragon','tipping over nw0004.bmp'),
                         os.path.join('graphics','dragon','tipping over nw0005.bmp'),
                         os.path.join('graphics','dragon','tipping over nw0006.bmp'),
                         os.path.join('graphics','dragon','tipping over nw0007.bmp'),
                         os.path.join('graphics','dragon','tipping over nw0008.bmp'),
                         os.path.join('graphics','dragon','tipping over nw0009.bmp'),
                         os.path.join('graphics','dragon','tipping over nw0010.bmp')],
                  's': [os.path.join('graphics','dragon','tipping over s0000.bmp'),
                        os.path.join('graphics','dragon','tipping over s0001.bmp'),
                        os.path.join('graphics','dragon','tipping over s0002.bmp'),
                        os.path.join('graphics','dragon','tipping over s0003.bmp'),
                        os.path.join('graphics','dragon','tipping over s0004.bmp'),
                        os.path.join('graphics','dragon','tipping over s0005.bmp'),
                        os.path.join('graphics','dragon','tipping over s0006.bmp'),
                        os.path.join('graphics','dragon','tipping over s0007.bmp'),
                        os.path.join('graphics','dragon','tipping over s0008.bmp'),
                        os.path.join('graphics','dragon','tipping over s0009.bmp'),
                        os.path.join('graphics','dragon','tipping over s0010.bmp')],
                  'se': [os.path.join('graphics','dragon','tipping over se0000.bmp'),
                         os.path.join('graphics','dragon','tipping over se0001.bmp'),
                         os.path.join('graphics','dragon','tipping over se0002.bmp'),
                         os.path.join('graphics','dragon','tipping over se0003.bmp'),
                         os.path.join('graphics','dragon','tipping over se0004.bmp'),
                         os.path.join('graphics','dragon','tipping over se0005.bmp'),
                         os.path.join('graphics','dragon','tipping over se0006.bmp'),
                         os.path.join('graphics','dragon','tipping over se0007.bmp'),
                         os.path.join('graphics','dragon','tipping over se0008.bmp'),
                         os.path.join('graphics','dragon','tipping over se0009.bmp'),
                         os.path.join('graphics','dragon','tipping over se0010.bmp')],
                  'sw': [os.path.join('graphics','dragon','tipping over sw0000.bmp'),
                         os.path.join('graphics','dragon','tipping over sw0001.bmp'),
                         os.path.join('graphics','dragon','tipping over sw0002.bmp'),
                         os.path.join('graphics','dragon','tipping over sw0003.bmp'),
                         os.path.join('graphics','dragon','tipping over sw0004.bmp'),
                         os.path.join('graphics','dragon','tipping over sw0005.bmp'),
                         os.path.join('graphics','dragon','tipping over sw0006.bmp'),
                         os.path.join('graphics','dragon','tipping over sw0007.bmp'),
                         os.path.join('graphics','dragon','tipping over sw0008.bmp'),
                         os.path.join('graphics','dragon','tipping over sw0009.bmp'),
                         os.path.join('graphics','dragon','tipping over sw0010.bmp')],
                  'w': [os.path.join('graphics','dragon','tipping over w0000.bmp'),
                        os.path.join('graphics','dragon','tipping over w0001.bmp'),
                        os.path.join('graphics','dragon','tipping over w0002.bmp'),
                        os.path.join('graphics','dragon','tipping over w0003.bmp'),
                        os.path.join('graphics','dragon','tipping over w0004.bmp'),
                        os.path.join('graphics','dragon','tipping over w0005.bmp'),
                        os.path.join('graphics','dragon','tipping over w0006.bmp'),
                        os.path.join('graphics','dragon','tipping over w0007.bmp'),
                        os.path.join('graphics','dragon','tipping over w0008.bmp'),
                        os.path.join('graphics','dragon','tipping over w0009.bmp'),
                        os.path.join('graphics','dragon','tipping over w0010.bmp')]},
 'walking': {'e': [os.path.join('graphics','dragon','walking e0000.bmp'),
                   os.path.join('graphics','dragon','walking e0001.bmp'),
                   os.path.join('graphics','dragon','walking e0002.bmp'),
                   os.path.join('graphics','dragon','walking e0003.bmp'),
                   os.path.join('graphics','dragon','walking e0004.bmp'),
                   os.path.join('graphics','dragon','walking e0005.bmp'),
                   os.path.join('graphics','dragon','walking e0006.bmp'),
                   os.path.join('graphics','dragon','walking e0007.bmp'),
                   os.path.join('graphics','dragon','walking e0008.bmp')],
             'n': [os.path.join('graphics','dragon','walking n0000.bmp'),
                   os.path.join('graphics','dragon','walking n0001.bmp'),
                   os.path.join('graphics','dragon','walking n0002.bmp'),
                   os.path.join('graphics','dragon','walking n0003.bmp'),
                   os.path.join('graphics','dragon','walking n0004.bmp'),
                   os.path.join('graphics','dragon','walking n0005.bmp'),
                   os.path.join('graphics','dragon','walking n0006.bmp'),
                   os.path.join('graphics','dragon','walking n0007.bmp'),
                   os.path.join('graphics','dragon','walking n0008.bmp')],
             'ne': [os.path.join('graphics','dragon','walking ne0000.bmp'),
                    os.path.join('graphics','dragon','walking ne0001.bmp'),
                    os.path.join('graphics','dragon','walking ne0002.bmp'),
                    os.path.join('graphics','dragon','walking ne0003.bmp'),
                    os.path.join('graphics','dragon','walking ne0004.bmp'),
                    os.path.join('graphics','dragon','walking ne0005.bmp'),
                    os.path.join('graphics','dragon','walking ne0006.bmp'),
                    os.path.join('graphics','dragon','walking ne0007.bmp'),
                    os.path.join('graphics','dragon','walking ne0008.bmp')],
             'nw': [os.path.join('graphics','dragon','walking nw0000.bmp'),
                    os.path.join('graphics','dragon','walking nw0001.bmp'),
                    os.path.join('graphics','dragon','walking nw0002.bmp'),
                    os.path.join('graphics','dragon','walking nw0003.bmp'),
                    os.path.join('graphics','dragon','walking nw0004.bmp'),
                    os.path.join('graphics','dragon','walking nw0005.bmp'),
                    os.path.join('graphics','dragon','walking nw0006.bmp'),
                    os.path.join('graphics','dragon','walking nw0007.bmp'),
                    os.path.join('graphics','dragon','walking nw0008.bmp')],
             's': [os.path.join('graphics','dragon','walking s0000.bmp'),
                   os.path.join('graphics','dragon','walking s0001.bmp'),
                   os.path.join('graphics','dragon','walking s0002.bmp'),
                   os.path.join('graphics','dragon','walking s0003.bmp'),
                   os.path.join('graphics','dragon','walking s0004.bmp'),
                   os.path.join('graphics','dragon','walking s0005.bmp'),
                   os.path.join('graphics','dragon','walking s0006.bmp'),
                   os.path.join('graphics','dragon','walking s0007.bmp'),
                   os.path.join('graphics','dragon','walking s0008.bmp')],
             'se': [os.path.join('graphics','dragon','walking se0000.bmp'),
                    os.path.join('graphics','dragon','walking se0001.bmp'),
                    os.path.join('graphics','dragon','walking se0002.bmp'),
                    os.path.join('graphics','dragon','walking se0003.bmp'),
                    os.path.join('graphics','dragon','walking se0004.bmp'),
                    os.path.join('graphics','dragon','walking se0005.bmp'),
                    os.path.join('graphics','dragon','walking se0006.bmp'),
                    os.path.join('graphics','dragon','walking se0007.bmp'),
                    os.path.join('graphics','dragon','walking se0008.bmp')],
             'sw': [os.path.join('graphics','dragon','walking sw0000.bmp'),
                    os.path.join('graphics','dragon','walking sw0001.bmp'),
                    os.path.join('graphics','dragon','walking sw0002.bmp'),
                    os.path.join('graphics','dragon','walking sw0003.bmp'),
                    os.path.join('graphics','dragon','walking sw0004.bmp'),
                    os.path.join('graphics','dragon','walking sw0005.bmp'),
                    os.path.join('graphics','dragon','walking sw0006.bmp'),
                    os.path.join('graphics','dragon','walking sw0007.bmp'),
                    os.path.join('graphics','dragon','walking sw0008.bmp')],
             'w': [os.path.join('graphics','dragon','walking w0000.bmp'),
                   os.path.join('graphics','dragon','walking w0001.bmp'),
                   os.path.join('graphics','dragon','walking w0002.bmp'),
                   os.path.join('graphics','dragon','walking w0003.bmp'),
                   os.path.join('graphics','dragon','walking w0004.bmp'),
                   os.path.join('graphics','dragon','walking w0005.bmp'),
                   os.path.join('graphics','dragon','walking w0006.bmp'),
                   os.path.join('graphics','dragon','walking w0007.bmp'),
                   os.path.join('graphics','dragon','walking w0008.bmp')]}}


if __name__=='__main__':
    #initial setup
    '''
    knight_images=Image_lib(os.path.join('C:','Documents and Settings','Gregory\My Documents\DragonFighter\graphics\knight'))
    knight_images.load(['attack','running','walking','paused','been hit','tipping over'])
    knight_images.save('knight d.txt')

    dragon_images=Image_lib(os.path.join('C:','Documents and Settings','Gregory\My Documents\DragonFighter\graphics\dragon'))
    dragon_images.load(['attack','running','walking','paused','reading','tipping over'])
    dragon_images.save('dragon d.txt')
    '''
    pass